<!DOCTYPE HTML>
<html>
<head>
    <meta name="viewport" content="width=device-width">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <?php foreach ($data['data'] as $v): ?>
        <div>
            <p><?php echo $v['title']?></p>
            <div><img src="<?php echo $v['img_path']?>" style="max-width: 300px;"></div>
            <p><?php echo money_format('%i', $v['price'])?></p>
        </div>
    <?php endforeach;?>

    <?php include "includes/pagination.phtml" ?>
</div>
</body>
</html>
